name: release_binaries
on:
  release:
    types: created

jobs:
  macos:
    name: Add macOS binaries to release
    runs-on: macOS-latest
    env:
      XCODE_VERSION: ${{ '11.4' }}
      GIT_REF: ${{ github.ref }}
    steps:
      - name: Select Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: swift build -c release
      - name: Zip release
        run: "mkdir releases && zip -j releases/SwiftActions-macOS-amd64-${GIT_REF:10}.zip .build/release/SwiftActions"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

  linux:
    name: Add Linux binaries to release
    runs-on: ubuntu-latest
    container:
      image: swift:5.2
    env:
      GIT_REF: ${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: LANG=en_US.UTF-8 LC_CTYPE=UTF-8 swift build -c release
      - name: Zip release
        run: "mkdir releases && zip -j releases/SwiftActions-linux-amd64-${GIT_REF:10}.zip .build/release/SwiftActions"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
